import { chromium } from "@playwright/test";
const out = process.argv[2] || "/tmp/flow";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium", args: ["--use-gl=swiftshader", "--enable-unsafe-swiftshader"] });
const p = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const logs = [];
p.on("console", m => logs.push(m.type() + ": " + m.text()));
p.on("pageerror", e => logs.push("pageerror: " + e.message));
await p.goto("http://localhost:4173/goc-pho-viet/");
await p.waitForTimeout(700); await p.screenshot({ path: out + "-1splash.png" });
await p.waitForSelector(".loading", { timeout: 15000 }); await p.waitForTimeout(1300); await p.screenshot({ path: out + "-2loading.png" });
await p.waitForFunction(() => window.__gpv?.ready, null, { timeout: 60000 });
await p.screenshot({ path: out + "-3menu.png" });
await p.click('[data-menu="new"]'); await p.waitForTimeout(400); await p.screenshot({ path: out + "-4new.png" });
await p.click('[data-panel="start"]'); await p.waitForFunction(() => window.__gpv.screen === "game"); await p.waitForTimeout(800);
await p.screenshot({ path: out + "-5game.png" });
await p.click('[data-action="settings"]'); await p.waitForTimeout(400); await p.screenshot({ path: out + "-6settings.png" });
await p.click('[data-panel="to-menu"]'); await p.waitForFunction(() => window.__gpv.screen === "menu"); await p.waitForTimeout(800);
await p.screenshot({ path: out + "-7menu2.png" });
console.log(JSON.stringify(await p.evaluate(() => window.__gpv.loadingHistory)));
console.log(logs.join("\n"));
await b.close();
