import { chromium } from "@playwright/test";
const b = await chromium.launch({ executablePath: process.env.PW_CHROMIUM || "/opt/pw-browsers/chromium", args: ["--use-gl=swiftshader", "--enable-unsafe-swiftshader"] });
const p = await b.newPage({ viewport: { width: 430, height: 932 }, deviceScaleFactor: 3, isMobile: true, hasTouch: true });
const logs = [];
p.on("console", m => logs.push(m.type() + ": " + m.text()));
p.on("pageerror", e => logs.push("pageerror: " + e.message));
await p.goto("http://localhost:4173/goc-pho-viet/");
await p.waitForFunction(() => window.__gpv?.ready, null, { timeout: 15000 });
await p.waitForTimeout(500);
await p.screenshot({ path: "/tmp/s430.png" });
console.log(JSON.stringify(await p.evaluate(() => window.__gpv.world.stats)));
console.log(logs.join("\n"));
await b.close();
